# Generated by Django 4.2.4 on 2023-08-06 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('undef', ''), ('buisness', 'Бизнес'), ('finance', 'Финансы'), ('traveling', 'Путишествия')], default='undef')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('update_time', models.TimeField()),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='telegram.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('telegram', 'Telegram')], default='telegram')),
            ],
        ),
        migrations.CreateModel(
            name='Promts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('promt_text', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promts', to='telegram.projects')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='sourses',
            field=models.ManyToManyField(related_name='projects', to='telegram.sources'),
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('post_text', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='telegram.sources')),
            ],
        ),
        migrations.CreateModel(
            name='GptPosts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpt_posts', to='telegram.projects')),
                ('promt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpt_posts', to='telegram.promts')),
            ],
        ),
    ]
