# Generated by Django 4.2.4 on 2023-08-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='title',
            field=models.CharField(choices=[('undef', ''), ('buisness', 'Бизнес'), ('finance', 'Финансы'), ('traveling', 'Путешествия')], default='undef'),
        ),
    ]
