# Generated by Django 4.2.4 on 2023-08-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_groups_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
