# Generated by Django 4.2.4 on 2023-08-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_sources_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='current_promt',
            field=models.IntegerField(null=True),
        ),
    ]
