# Generated by Django 4.2.4 on 2023-08-14 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_projects_current_promt'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptposts',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
