# Generated by Django 4.2.4 on 2023-08-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_gptposts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='source_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='telegram.sources'),
        ),
    ]
