# Generated by Django 4.2.4 on 2023-08-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0007_tguser_posts_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
