# Generated by Django 4.2.4 on 2023-08-23 19:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0009_alter_tguser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptposts',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gptposts',
            name='long_type',
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
    ]
