# Generated by Django 4.2.4 on 2023-08-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0010_gptposts_creation_date_gptposts_long_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gptposts',
            options={'ordering': ['-creation_date']},
        ),
    ]
