# Generated by Django 4.2.4 on 2023-08-23 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0011_alter_gptposts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gptposts',
            options={'ordering': ['-creation_date', '-date']},
        ),
    ]
